//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTienNghi
    {
        public int ID { get; set; }
        public string MaChiTietTienNghi { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<int> MaTienNghi { get; set; }
        public Nullable<int> MaPhong { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual TienNghi TienNghi { get; set; }
    }
}
