//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuThue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietPhieuThue()
        {
            this.DichVuPhongs = new HashSet<DichVuPhong>();
        }
    
        public int ID { get; set; }
        public string MaChiTietPhieuThue { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<int> MaPhieuThue { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> TienPhong { get; set; }
    
        public virtual PhieuThue PhieuThue { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVuPhong> DichVuPhongs { get; set; }
    }
}
